# Site settings
name: Less Or More
email: jennifer.ooooh@gmail.com
author: JenniferOh
url: 'https://jenniferoh.github.io/og.github.io/'
resume_site: https://www.linkedin.com/in/jennifer-oh-15223412a/
github: https://github.com/JenniferOH/og.github.io
baseurl: "/og.github.io"
description: Actually, less is more!
meta_description: 오지는 블로그
motto: It's our wits that make us men.
banner: 블라블라

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoyan35714

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

